// EduKids Student Theme Utility
// This file provides theme lookup and condition definitions used by the student app.

export const THEMES = {
  normal: {
    name: "normal",
    label: "Standard",
    emoji: "🌟",
    colors: {
      primary: "#7C3AED",
      primaryLight: "#A78BFA",
      primaryDark: "#5B21B6",
      secondary: "#F59E0B",
      accent: "#10B981",
      background: "#FFF8F0",
      backgroundGradient: "linear-gradient(135deg, #FFF8F0 0%, #FDF4FF 50%, #F0FDF4 100%)",
      surface: "#FFFFFF",
      surfaceHover: "#F9F5FF",
      text: "#1F2937",
      textSecondary: "#6B7280",
      textMuted: "#9CA3AF",
      border: "#E5E7EB",
      cardShadow: "0 4px 24px rgba(124,58,237,0.08)",
      cardShadowHover: "0 8px 40px rgba(124,58,237,0.18)",
      badge: "#EDE9FE",
      badgeText: "#6D28D9",
      buttonGradient: "linear-gradient(135deg, #7C3AED, #A855F7)",
      headerGradient: "linear-gradient(135deg, #7C3AED 0%, #A855F7 100%)",
      floatingStar: "rgba(124,58,237,0.15)",
    },
    fonts: {
      heading: "'Nunito', sans-serif",
      body: "'Nunito', sans-serif",
      size: "16px",
      lineHeight: "1.6",
      letterSpacing: "normal",
    },
    spacing: "normal",
    borderRadius: "16px",
    animations: true,
  },

  autism: {
    name: "autism",
    label: "Autism-Friendly",
    emoji: "🌈",
    colors: {
      primary: "#0EA5E9",
      primaryLight: "#7DD3FC",
      primaryDark: "#0284C7",
      secondary: "#F97316",
      accent: "#22C55E",
      background: "#F8FAFF",
      backgroundGradient: "linear-gradient(135deg, #F0F9FF 0%, #F8FAFF 100%)",
      surface: "#FFFFFF",
      surfaceHover: "#F0F9FF",
      text: "#0F172A",
      textSecondary: "#475569",
      textMuted: "#94A3B8",
      border: "#CBD5E1",
      cardShadow: "0 2px 16px rgba(14,165,233,0.08)",
      cardShadowHover: "0 4px 24px rgba(14,165,233,0.16)",
      badge: "#E0F2FE",
      badgeText: "#0369A1",
      buttonGradient: "linear-gradient(135deg, #0EA5E9, #38BDF8)",
      headerGradient: "linear-gradient(135deg, #0EA5E9 0%, #38BDF8 100%)",
      floatingStar: "rgba(14,165,233,0.12)",
    },
    fonts: {
      heading: "'Lexend', sans-serif",
      body: "'Lexend', sans-serif",
      size: "17px",
      lineHeight: "1.8",
      letterSpacing: "0.02em",
    },
    spacing: "relaxed",
    borderRadius: "20px",
    animations: false,
    notes: "High contrast, predictable layout, reduced animations, clear visual hierarchy",
  },

  dyslexia: {
    name: "dyslexia",
    label: "Dyslexia-Friendly",
    emoji: "📖",
    colors: {
      primary: "#D97706",
      primaryLight: "#FCD34D",
      primaryDark: "#B45309",
      secondary: "#7C3AED",
      accent: "#059669",
      background: "#FEFCE8",
      backgroundGradient: "linear-gradient(135deg, #FEFCE8 0%, #FFFBF0 100%)",
      surface: "#FFFFF0",
      surfaceHover: "#FEFCE8",
      text: "#1C1008",
      textSecondary: "#44403C",
      textMuted: "#78716C",
      border: "#D6D3D1",
      cardShadow: "0 3px 20px rgba(217,119,6,0.10)",
      cardShadowHover: "0 6px 32px rgba(217,119,6,0.20)",
      badge: "#FEF3C7",
      badgeText: "#92400E",
      buttonGradient: "linear-gradient(135deg, #D97706, #F59E0B)",
      headerGradient: "linear-gradient(135deg, #D97706 0%, #F59E0B 100%)",
      floatingStar: "rgba(217,119,6,0.12)",
    },
    fonts: {
      heading: "'Lexend Deca', sans-serif",
      body: "'Atkinson Hyperlegible', sans-serif",
      size: "18px",
      lineHeight: "2.0",
      letterSpacing: "0.05em",
    },
    spacing: "wide",
    borderRadius: "12px",
    animations: true,
    notes: "Cream background reduces visual stress, wider line spacing, larger text, no justified text",
  },

  adhd: {
    name: "adhd",
    label: "ADHD-Friendly",
    emoji: "⚡",
    colors: {
      primary: "#EC4899",
      primaryLight: "#F9A8D4",
      primaryDark: "#BE185D",
      secondary: "#8B5CF6",
      accent: "#06B6D4",
      background: "#FFF0F6",
      backgroundGradient: "linear-gradient(135deg, #FFF0F6 0%, #F5F3FF 50%, #F0FDFF 100%)",
      surface: "#FFFFFF",
      surfaceHover: "#FFF0F6",
      text: "#1E1B4B",
      textSecondary: "#4C1D95",
      textMuted: "#7C3AED",
      border: "#DDD6FE",
      cardShadow: "0 4px 20px rgba(236,72,153,0.10)",
      cardShadowHover: "0 8px 36px rgba(236,72,153,0.22)",
      badge: "#FCE7F3",
      badgeText: "#9D174D",
      buttonGradient: "linear-gradient(135deg, #EC4899, #A855F7)",
      headerGradient: "linear-gradient(135deg, #EC4899 0%, #8B5CF6 100%)",
      floatingStar: "rgba(236,72,153,0.15)",
    },
    fonts: {
      heading: "'Fredoka One', cursive",
      body: "'Nunito', sans-serif",
      size: "16px",
      lineHeight: "1.7",
      letterSpacing: "0.01em",
    },
    spacing: "normal",
    borderRadius: "24px",
    animations: true,
    notes: "Vibrant engaging colors, chunked content, frequent rewards, progress indicators",
  },
};

export const getTheme = (condition) => THEMES[condition] || THEMES.normal;

export const CONDITIONS = [
  { id: "normal",   label: "Standard",  emoji: "🌟", desc: "Regular learning experience" },
  { id: "autism",   label: "Autism",    emoji: "🌈", desc: "Calm, structured & predictable" },
  { id: "dyslexia", label: "Dyslexia",  emoji: "📖", desc: "Easy-to-read typography" },
  { id: "adhd",     label: "ADHD",      emoji: "⚡", desc: "Engaging & focused" },
];
